### ISSUE TITLE
Dynamic Recipients for Notification Emails

### ISSUE THREAD

**Issue by moacode** [barrelstrength/sprout-email#129]
### The problem (description, use case, screenshots...)
I'd like to be able to dynamically set the recipients from a custom event. I.e. I've setup an event that fires once an order has been paid for in Commerce, and I'd like to set the recipient as the customer.

### The solution (that feature you'd like to see)
Either being able to register a custom Mailer (I see the `EmailElement` is hardcoded to returning `DefaultMailer`), or being able to set recipients from the event object would be useful.

### Alternatives you've considered
Tried to hook into the `setOnTheFlyRecipients` method on the `RecipientsTrait` without success.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_18bpf)

**Comment by BenParizek** [comment]
@thejoshsmith We're working toward making this possible. I can't promise a timeline but will update this thread when we have more to share.

**Comment by thejoshsmith** [comment]
Brilliant, thanks for the update @BenParizek!
