### ISSUE TITLE
Unable to render notification preview template

### ISSUE THREAD

**Issue by johnj24** [barrelstrength/sprout-email#181]
### Description (screenshots, logs, ...)
Recently updated to the latest Craft and Sprout Email versions and I'm getting this error whenever I publish an entry assigned to an email notification, or try and preview an email notification within the control panel:

Argument 1 passed to craft\web\View::renderTemplate() must be of the type string, null given, called in /Users/jjohnson/Sites/localhost/grandrail/vendor/barrelstrength/sprout-base-email/src/base/EmailTemplates.php on line 145

### Steps to reproduce

1. Sprout Email > Notifications > Preview
2. The error is displayed in the pop-up window

### Additional info

- Craft version: 3.6.16
- PHP version: 7.3.21
- Database driver & version:  MySQL 5.7.30
- Plugins & versions: Sprout Email 4.4.9

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@johnj24 Sounds like something may be off with the template settings. Maybe we have a bug in a migration. I'll have to review.

In the meantime, you can probably resolve it by revisiting the Sprout Email->Settings 'Default Email Templates' and,if you have custom templates on a per-email basis, review the individual Email Templates setting.

If you are using custom templates, make sure the Custom Tempaltes setting only references the folder "_email" and that will resolve to your email template by dynamically adding the email file "_email/email.html" or "_email/email.twig"
